version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: safevault-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_Password123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - safevault-net
    volumes:
      - sql_data:/var/opt/mssql

  payment-mock-service:
    build:
      context: ./payment-mock
    container_name: safevault-payment-mock
    ports:
      - "9090:3000"
    networks:
      - safevault-net

  safevault-api:
    build:
      context: .
      dockerfile: SafeVaultApi/Dockerfile
    container_name: safevault-api
    depends_on:
      - sqlserver
      - payment-mock-service
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver,1433;Database=SafeVaultDb;User Id=sa;Password=Your_Password123!;TrustServerCertificate=True;
      PaymentApi__BaseUrl: "http://payment-mock-service:3000"
    ports:
      - "8080:8080"
    networks:
      - safevault-net

  safevault-functional-tests:
    build:
      context: .
      dockerfile: tests/SafeVault.FunctionalTests/Dockerfile
    container_name: safevault-functional-tests
    depends_on:
      - safevault-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ApiBaseUrl: "http://safevault-api:8080"
    networks:
      - safevault-net
    # Don't shutdown everything automatically
    command: ["dotnet", "test", "--logger:trx"]

networks:
  safevault-net:

volumes:
  sql_data:
